
import DAO.TheDocGiaDAO;
import DAO.tblchitietphieumuonDAO;
import DAO.tblphieumuonsachDAO;
import UserTableModel.SachTableModel;
import entity.tblchitietphieumuon;
import entity.tblphieumuonsach;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import tools.TheDocGiaComboModel;
import tools.TinhThang;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hau
 */
public class frmGUI extends javax.swing.JFrame {

    public static String bundlea = "abc";
    /**
     * Creates new form frmTimTraMuonSach
     *
     */
    TableModel tableModel = createTableModel();

    DefaultTableModel dm = new DefaultTableModel();

    String[] dsTheDocGia = TheDocGiaDAO.layDanhSachTenDocGia();
    TheDocGiaComboModel cbModelTheDocGia;

    TableModel tmChon = createTableModelSachChuaMuon();
    String[] dsMaTheDocGia = TheDocGiaDAO.layDanhSachMaTheDocGia();
    int SoSachDaMuon = 0;

    public frmGUI() {
        cbModelTheDocGia = new TheDocGiaComboModel(dsTheDocGia);
        dm.setColumnIdentifiers(new Object[]{"STT", "Mã sách", "Tên sách", "Thể loại", "Tác giả"});
        initComponents();
        txtLoi.setVisible(false);
        Date date = new Date();
        dtpNgayMuon.setFormats(new String[]{"dd/MM/yyyy"});
        dtpNgayMuon.setDate(date);
        tbMuon.setDefaultEditor(Object.class, null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        //Hien sach con lai
        String[] DSPhieuMuonHienTai = tblphieumuonsachDAO.layDSPhieuMuonSachBangMaTheDocGia(dsMaTheDocGia[cbbMaTheDocGia.getSelectedIndex()], new Date());
        SoSachDaMuon = DSPhieuMuonHienTai.length;
        txtSoSachConLai.setText(String.valueOf(SoSachDaMuon));

        cbbMaTheDocGia.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                if (kiemTraHan()) {
                    txtSoSachConLai.setText("0");
                    txtSoSachDangChon.setText("0");
                    return;
                }
                if (kiemTra4Ngay()) {
                    return;
                }
                txtSoSachDangChon.setText(String.valueOf(tbMuon.getRowCount()));
                JComboBox comboBox = (JComboBox) event.getSource();

                String[] DSPhieuMuonHienTai = tblphieumuonsachDAO.layDSPhieuMuonSachBangMaTheDocGia(dsMaTheDocGia[cbbMaTheDocGia.getSelectedIndex()], new Date());
                SoSachDaMuon = DSPhieuMuonHienTai.length;
                txtSoSachConLai.setText(String.valueOf(DSPhieuMuonHienTai.length + dm.getRowCount()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jFrame1 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable(tableModel);
        jTextField2 = RowFilterUtil.createRowFilter(tbSach);
        pnlMuonSach = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbbMaTheDocGia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMuon = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLuuPhieu = new javax.swing.JButton();
        dtpNgayMuon = new org.jdesktop.swingx.JXDatePicker();
        txtLoi = new javax.swing.JLabel();
        txtConLai = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoSachConLai = new javax.swing.JLabel();
        txtConLai1 = new javax.swing.JLabel();
        txtSoSachDangChon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLoaiDocGia = new javax.swing.JLabel();
        cboLoaiDocGia = new javax.swing.JComboBox<>();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        btnThem1 = new javax.swing.JButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnXoa1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Tìm kiếm");

        tbSach.setModel(
            tableModel
        );
        jScrollPane1.setViewportView(tbSach);

        jTextField2.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(79, 79, 79))
        );

        jTabbedPane1.addTab("Tra cứu sách", jPanel1);

        jLabel2.setText("Họ tên đọc giả");

        cbbMaTheDocGia.setModel(cbModelTheDocGia);

        jLabel3.setText("Ngày mượn");

        tbMuon.setModel(dm);
        jScrollPane3.setViewportView(tbMuon);

        btnXoa.setText("Xóa sách");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm sách");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuuPhieu.setText("Lưu phiếu");
        btnLuuPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPhieuActionPerformed(evt);
            }
        });

        txtLoi.setForeground(new java.awt.Color(255, 0, 0));
        txtLoi.setText("Lỗi");

        txtConLai.setForeground(new java.awt.Color(0, 0, 255));
        txtConLai.setText("Số sách mượn:");

        txtSoSachConLai.setText("jLabel5");

        txtConLai1.setForeground(new java.awt.Color(0, 0, 255));
        txtConLai1.setText("Số sách đang chọn:");

        txtSoSachDangChon.setText("0");

        javax.swing.GroupLayout pnlMuonSachLayout = new javax.swing.GroupLayout(pnlMuonSach);
        pnlMuonSach.setLayout(pnlMuonSachLayout);
        pnlMuonSachLayout.setHorizontalGroup(
            pnlMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMuonSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(pnlMuonSachLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMuonSachLayout.createSequentialGroup()
                        .addGroup(pnlMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMuonSachLayout.createSequentialGroup()
                                .addComponent(txtLoi)
                                .addGap(177, 177, 177)
                                .addComponent(jLabel4)
                                .addGap(12, 12, 12)
                                .addComponent(txtConLai)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoSachConLai)
                                .addGap(18, 18, 18)
                                .addComponent(txtConLai1)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoSachDangChon))
                            .addGroup(pnlMuonSachLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbMaTheDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(dtpNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMuonSachLayout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(26, 26, 26)
                        .addComponent(btnXoa)
                        .addGap(35, 35, 35)
                        .addComponent(btnLuuPhieu)
                        .addGap(190, 190, 190))))
        );
        pnlMuonSachLayout.setVerticalGroup(
            pnlMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMuonSachLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbMaTheDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dtpNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtConLai1)
                        .addComponent(txtSoSachDangChon))
                    .addGroup(pnlMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLoi)
                        .addComponent(txtConLai)
                        .addComponent(jLabel4)
                        .addComponent(txtSoSachConLai)))
                .addGap(18, 18, 18)
                .addGroup(pnlMuonSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnThem)
                    .addComponent(btnLuuPhieu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Phiếu mượn sách", pnlMuonSach);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lblTitle.setText("Quản Lý Thẻ Độc Giả");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Thẻ", 0, 0, new java.awt.Font("Times New Roman", 0, 20))); // NOI18N
        jPanel3.setToolTipText("");
        jPanel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblLoaiDocGia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblLoaiDocGia.setText("Loại đọc giả:");

        cboLoaiDocGia.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cboLoaiDocGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));

        lblHoTen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHoTen.setText("Họ tên:");

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblDiaChi.setText("Địa chỉ:");

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEmail.setText("Email:");

        lblNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNgaySinh.setText("Ngày sinh:");

        btnThem1.setBackground(new java.awt.Color(204, 255, 204));
        btnThem1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThem1.setText("Thêm Thẻ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoaiDocGia)
                            .addComponent(lblHoTen)
                            .addComponent(lblDiaChi)
                            .addComponent(lblEmail)
                            .addComponent(lblNgaySinh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiaChi)
                            .addComponent(cboLoaiDocGia, 0, 150, Short.MAX_VALUE)
                            .addComponent(txtHoTen)
                            .addComponent(txtEmail)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaiDocGia)
                    .addComponent(cboLoaiDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgaySinh)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Thẻ Đọc Giả", 0, 0, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnXoa1.setBackground(new java.awt.Color(255, 102, 102));
        btnXoa1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXoa1.setText("Xóa Thẻ Đang Chọn");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(222, 222, 222))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý thẻ đọc giả", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dtpNgayMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtpNgayMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtpNgayMuonActionPerformed

    private Boolean kiemTra4Ngay() {
        String[] Sach4Ngay = tblphieumuonsachDAO.layDSKiemTraNgayMuon(dsMaTheDocGia[cbbMaTheDocGia.getSelectedIndex()], new Date());

        if (Sach4Ngay.length > 0) {
            txtLoi.setVisible(true);
            txtLoi.setForeground(Color.RED);
            txtLoi.setText("Tài khoản mượn sách quá 4 ngày");
            return true;
        } else {
            return false;
        }
    }

    private Boolean kiemTraHan() {
        Date now = new Date();
        Date NgayLapThe = TheDocGiaDAO.layNgayLapBangMaThe(dsMaTheDocGia[cbbMaTheDocGia.getSelectedIndex()]);
        //        System.out.println("Ngay Lap The: " + NgayLapThe);
        Calendar cal1 = Calendar.getInstance();
        cal1.set(NgayLapThe.getYear(), NgayLapThe.getMonth(), NgayLapThe.getDate());
        Calendar cal2 = Calendar.getInstance();
        cal2.set(now.getYear(), now.getMonth(), now.getDate());
        boolean valid = TinhThang.isSixMonthsAgo(cal2, cal1);

        // System.out.println("Kiem tra 6 thang: " + valid);
        if (valid) {
            txtLoi.setVisible(true);
            txtLoi.setForeground(Color.RED);
            txtLoi.setText("Thẻ quá hạn.");
        } else {
            txtLoi.setForeground(Color.GREEN);
            txtLoi.setVisible(false);
        }
        return valid;
    }

    private void btnLuuPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPhieuActionPerformed

        if (kiemTraHan()) {
            return;
        }
        if (kiemTra4Ngay()) {
            return;
        }
        Date now = new Date();

        String[] DSPhieuMuonHienTai = tblphieumuonsachDAO.layDSPhieuMuonSachBangMaTheDocGia(dsMaTheDocGia[cbbMaTheDocGia.getSelectedIndex()], now);
        if (DSPhieuMuonHienTai.length > 4) {
            txtLoi.setVisible(true);
            txtLoi.setForeground(Color.RED);
            txtLoi.setText("Chỉ được mượn tối đa 5 quyển");
            return;
        }
        System.out.println("DanhSachPhieuDangMuon: " + DSPhieuMuonHienTai.length);
        if (tbMuon.getModel().getRowCount() == 0) {
            txtLoi.setVisible(true);
            txtLoi.setForeground(Color.RED);
            txtLoi.setText("Chưa chọn sách");
            return;
        }

        tblphieumuonsach t = new tblphieumuonsach();
        t.setMaTheDocGia(Integer.parseInt(dsMaTheDocGia[cbbMaTheDocGia.getSelectedIndex()]));
        Date NgayMuon = dtpNgayMuon.getDate();
        t.setNgayMuon(NgayMuon);
        t.setTrangThaiXoa(false);
        int newid = tblphieumuonsachDAO.themPhieuMuon(t);

        for (int i = 0; i < tbMuon.getRowCount(); i++) {
            tblchitietphieumuon ct = new tblchitietphieumuon();
            ct.setMaPhieuMuon(newid);

            int MaSach = Integer.parseInt(tbMuon.getModel().getValueAt(i, 1).toString());
            ct.setMaSach(MaSach);
            tblchitietphieumuonDAO.ThemChiTieuPhieuMuon(ct);
        }
        DefaultTableModel dmXoa = (DefaultTableModel) tbMuon.getModel();
        int rowCount = dmXoa.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dmXoa.removeRow(i);
        }

        txtLoi.setVisible(true);
        txtLoi.setForeground(Color.GREEN);
        txtLoi.setText("Thêm phiếu mượn thành công!");
    }//GEN-LAST:event_btnLuuPhieuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (kiemTraHan()) {
            return;
        }
        if (kiemTra4Ngay()) {
            return;
        }
        String[] DSPhieuMuonHienTai = tblphieumuonsachDAO.layDSPhieuMuonSachBangMaTheDocGia(dsMaTheDocGia[cbbMaTheDocGia.getSelectedIndex()], new Date());
        if (DSPhieuMuonHienTai.length + dm.getRowCount() > 4) {
            return;
        }

        ArrayList<String> danhSachDangChon = new ArrayList<>();

        for (int i = 0; i < dm.getRowCount(); i++) {
            String MaSach = dm.getValueAt(i, 1).toString();
            danhSachDangChon.add(MaSach);

        }
        System.out.println("Danh sach: " + danhSachDangChon.size());

        //DefaultTableModel dt = new DefaultTableModel(data, columnNames);
        JTable tbSach2 = new JTable();

        if (danhSachDangChon.size() > 0) {

            DefaultTableModel model = new DefaultTableModel(new String[]{"STT", "Mã Sách", "Tên Sách", "Thể loại", "Tác giả", "Tình trạng"}, 0);
            //TableModel n = new UserTableModel.SachTableModel("select * from tblsach");
            TableModel n = createTableModelSachChuaMuon();
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);
            }
            System.out.println("n.getRowCount(): " + n.getRowCount());
            for (int i = 0; i < n.getRowCount(); i++) {
                String cot1 = n.getValueAt(i, 1).toString();
                String cot2 = n.getValueAt(i, 2).toString();
                String cot3 = n.getValueAt(i, 3).toString();
                String cot4 = n.getValueAt(i, 4).toString();
                String cot5 = n.getValueAt(i, 5).toString();
                if (!danhSachDangChon.contains(cot1)) {
                    model.addRow(new Object[]{i, cot1, cot2, cot3, cot4, cot5});
                }
            }
            tbSach2.setModel(model);
        } else {
            tbSach2.setModel(createTableModelSachChuaMuon());
        }

        JScrollPane jScrollPane1 = new JScrollPane();

        jScrollPane1.setViewportView(tbSach2);

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(jScrollPane1);
        int result = JOptionPane.showConfirmDialog(null, panel, "Thêm Sách",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            if (tbSach2.getRowCount() > 0) {
                int column = 1;
                int row = tbSach2.getSelectedRow();

                String MaSach = tbSach2.getModel().getValueAt(row, column).toString();
                String TenSach = tbSach2.getModel().getValueAt(row, column + 1).toString();
                String TheLoai = tbSach2.getModel().getValueAt(row, column + 2).toString();
                String TacGia = tbSach2.getModel().getValueAt(row, column + 3).toString();
                Object[] newRowData = {tbMuon.getRowCount() + 1, MaSach, TenSach, TheLoai, TacGia};

                dm.addRow(newRowData);
                SoSachDaMuon += 1;
                // txtSoSachConLai.setText(String.valueOf(SoSachDaMuon));
                txtSoSachConLai.setText(String.valueOf(DSPhieuMuonHienTai.length + dm.getRowCount()));
                txtSoSachDangChon.setText(String.valueOf(tbMuon.getRowCount()));
            }
        } else {
            System.out.println("Cancelled");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        if (kiemTraHan()) {
            return;
        }
        if (kiemTra4Ngay()) {
            return;
        }
        dm.removeRow(tbMuon.getSelectedRow());
        String[] DSPhieuMuonHienTai = tblphieumuonsachDAO.layDSPhieuMuonSachBangMaTheDocGia(dsMaTheDocGia[cbbMaTheDocGia.getSelectedIndex()], new Date());
        txtSoSachConLai.setText(String.valueOf(DSPhieuMuonHienTai.length + dm.getRowCount()));
        txtSoSachDangChon.setText(String.valueOf(tbMuon.getRowCount()));
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGUI().setVisible(true);
            }
        });
    }

    private static TableModel createTableModel() {
        TableModel md = new UserTableModel.SachTableModel("select * from tblSach");
        return md;
    }

    private static TableModel createTableModelSachChuaMuon() {
        String sql = "select * from tblsach ts where ts.MaSach not in( select tc.MaSach from tblchitietphieumuon tc inner join tblphieumuonsach tm on tc.MaPhieuMuon = tm.MaPhieuMuon and tm.TrangThaiXoa = 0 )";
        TableModel md = new UserTableModel.SachTableModel(sql);
        return md;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuPhieu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JComboBox<String> cbbMaTheDocGia;
    private javax.swing.JComboBox<String> cboLoaiDocGia;
    private org.jdesktop.swingx.JXDatePicker dtpNgayMuon;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblLoaiDocGia;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlMuonSach;
    private javax.swing.JTable tbMuon;
    private javax.swing.JTable tbSach;
    private javax.swing.JLabel txtConLai;
    private javax.swing.JLabel txtConLai1;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JLabel txtLoi;
    private javax.swing.JLabel txtSoSachConLai;
    private javax.swing.JLabel txtSoSachDangChon;
    // End of variables declaration//GEN-END:variables
}
